### PR TITLE
cordova-lib 9.0.0 support

### PR DESCRIPTION
**Pull request by Scombr0**
Updates code to support cordova-lib 9.0.0.

Fixes error: `Using "requireCordovaModule" to load non-cordova module "semver" is not supported.`

It also adds fix for cordova 8.0.0 from PR: #13

### CODE REVIEW

**Comment by john-doherty** [comment]
Any chance this could be merged/published?

**Comment by ghost** [comment]
Does solve the problem!! We need this,

**Comment by Joaovtrc** [comment]
How do I use this on my project? 

`cordova plugin add https://github.com/blakgeek/cordova-plugin-app-name/d689ec4b9819cc823a0e3540a9e85692df889eae --variable APP_NAME="App Name" --save`


Like this?

**Comment by Joaovtrc** [comment]
> How do I use this on my project?
> 
> `cordova plugin add https://github.com/blakgeek/cordova-plugin-app-name/d689ec4b9819cc823a0e3540a9e85692df889eae --variable APP_NAME="App Name" --save`
> 
> Like this?

Managed to do this using it like this:

cordova plugin add git+https://github.com/blakgeek/cordova-plugin-app-name#d689ec4b9819cc823a0e3540a9e85692df889eae  --variable APP_NAME="App Name" --save

Just in case someone is having the same issue...

Thanks @Scombr0 for the fix!

**Comment by ghost** [comment]
hello, can you merge this pr ?

**Comment by gmatkovitch** [comment]
@blakgeek / @Scombr0 , can this pr be merged please?

**Comment by blakgeek** [comment]
This is fixed in version 1.0.7.

**Pull request closed without merging**
